barrio_comuna_mapping = {
    'AEROPUERTO': 'Comuna 7',
    'ALAMEDA': 'Comuna 5',
    'ALFONSO LOPEZ': 'Comuna 4',
    'ALTAMIRA': 'Comuna 2',
    'ALTOS DEL BOSQUE': 'Comuna 5',
    'BARRIO NUEVO': 'Comuna 7',
    'BENEDICTA': 'Comuna 2',
    'BERLIN': 'Comuna 2',
    'BIZERTA': 'Comuna 4',
    'BRISAS DEL BOLO': 'Comuna 3',
    'CAMPESTRE': 'Comuna 5',
    'CENTRO': 'Comuna 6',
    'CENTRO COMERCIAL LLANOGRANDE': 'Comuna 2',
    'CENTRO POBLADO BOYACA': 'Comuna 12',
    'CENTRO POBLADO LA HERRADURA': 'Comuna 9',
    'CENTRO POBLADO LA TORRE': 'Comuna 8',
    'CENTRO POBLADO POTRERILLO': 'Comuna 16',
    'CENTRO POBLADO ROZO': 'Comuna 8',
    'CHAPINERO': 'Comuna 7',
    'CHAPINERO SUR': 'Comuna 7',  # Asumo que esta variante de Chapinero está en la misma comuna.
    'COLOMBIA': 'Comuna 4',
    'COLOMBINA': 'Comuna 6',
    'CUIDAD DEL CAMPO': 'Comuna 5',  # Asumiendo basado en barrios cercanos.
    'DANUBIO': 'Comuna 5',
    'DELICIAS': 'Comuna 7',
    'DEPARTAMENTAL': 'Comuna 2',
    'EL SEMBRADOR': 'Comuna 7',
    'EMILIA': 'Comuna 3',
    'ESTONIA': 'Comuna 2',
    'FATIMA': 'Comuna 6',
    'FLORES': 'Comuna 5',  # Asumiendo basado en "Urb. Las Flores".
    'FRAY LUIS': 'Comuna 3',
    'GUAYACANES DEL SUR': 'Comuna 7',  # Asumiendo por proximidad a "Guayacanes del Ingenio".
    'INDUSTRIAL': 'Comuna 2',
    'INGENIO MANUELITA': 'Comuna 5',  # Asumiendo basado en barrios cercanos.
    'ITALCO PARQUIADERO': 'Comuna 5',  # Asumiendo basado en barrios cercanos.
    'ITALIA': 'Comuna 7',  # Basado en "Parques de la Italia".
    'JORGE ELIECER GAITAN': 'Comuna 4',
    'JUAN PABLO': 'Comuna 2',
    'LA DOLORES': 'Comuna 10',
    'LA TRINIDAD': 'Comuna 6',
    'LAS FLORES': 'Comuna 6',
    'LIBERTADORES': 'Comuna 6',
    'LORETO': 'Comuna 4',
    'LORETTO': 'Comuna 4',  # Asumo que esta variante de Loreto está en la misma comuna.
    'LOS MANGOS': 'Comuna 1',
    'LOS PINOS': 'Comuna 5',  # Asumiendo basado en barrios cercanos.
    'LOS ROBLES': 'Comuna 7',
    'LOS SAUCES': 'Comuna 5',
    'MERCEDES': 'Comuna 2',
    'MIRRIÑAO': 'Comuna 2',
    'MONTECLARO': 'Comuna 1',
    'MUNICIPAL': 'Comuna 5',
    'OBRERO': 'Comuna 4',
    'OLIMPICO': 'Comuna 3',
    'PALMIRA LOS CEIBOS': 'Comuna 6',  # Asumiendo basado en barrios cercanos.
    'PARAISO': 'Comuna 6',
    'POBLADO COMFAUNION': 'Comuna 1',
    'POMONA': 'Comuna 3',
    'POPULAR MODELO': 'Comuna 5',
    'PORTAL DE LAS PALMAS': 'Comuna 2',
    'PORTAL DEL SEMBRADOR': 'Comuna 7',
    'PORTALES DEL RECREO': 'Comuna 7',
    'PRADO': 'Comuna 3',
    'PRIMERO DE MAYO': 'Comuna 5',
    'RECREO': 'Comuna 7',
    'RESERVAS DE ZAMORANO': 'Comuna 1',
    'RINCON DE LAS FLORES': 'Comuna 5',  # Asumiendo basado en barrios cercanos.
    'RINCON DEL BOSQUE': 'Comuna 5',  # Asumiendo basado en barrios cercanos.
    'RIVERA ESCOBAR': 'Comuna 3',
    'SAMANES': 'Comuna 2',
    'SAN CAYETANO': 'Comuna 4',
    'SAN ISABEL': 'Comuna 2',
    'SAN PEDRO': 'Comuna 5',
    'SANTA ANA': 'Comuna 3',
    'SANTA BARBARA': 'Comuna 3',
    'SANTA ISABEL': 'Comuna 2',
    'SANTA MARIA DEL PALMAR': 'Comuna 2',
    'SANTA RITA': 'Comuna 4',
    'SANTA TERESITA': 'Comuna 2',
    'SEMBRADOR': 'Comuna 7',
    'SESQUI': 'Comuna 7',
    'SIMON BOLIVAR': 'Comuna 1',
    'TREBOL': 'Comuna 7',
    'TRINIDAD': 'Comuna 6',  # Asumiendo basado en barrios cercanos.
    'URIBE': 'Comuna 4',
    'VERSALLES': 'Comuna 2',
    'VIA CANDELARIA - PALMIRA': 'Comuna 16',  # Asumiendo por cercanía.
    'VIA AEROPUERTO ZONA FRANCA PALMASECA': 'Comuna 9',
    'VIA CALI - PALMIRA NORTE': 'Comuna 3',  # Asumiendo por ubicación.
    'VIA CALI - PALMIRA SUR': 'Comuna 6',  # Asumiendo por ubicación.
    'VILLA DEL SOL': 'Comuna 5',
    'VILLA ESPAÑA': 'Comuna 5',
    'VILLA HERMOSA': 'Comuna 2',
    'VILLA LIBERTADOR': 'Comuna 5',
    'VILLA SANTANDER': 'Comuna 6',
    'VILLA SUCRE': 'Comuna 5',
    'VILLAS DEL SEMBRADOR': 'Comuna 7',
    'ZAMORANO': 'Comuna 1',
}
